### ISSUE TITLE
[Bug] Remove ` tensorflow-io-gcs-filesystem`

### ISSUE THREAD

**Issue by 1chooo** [JunTingLin/magic-voice-switch#2]
We have to remove the `tensorflow-io-gcs-filesystem` dependency, or we might meet the unnecessary error when initializing the python environment.

https://github.com/JunTingLin/magic-voice-switch/blob/45333db8bb19d32a3aba6daa523d27d55dc86618/requirements.txt#L43

Assigned: @1chooo

**Comment by JunTingLin** [comment]
Got it. I have deleted that line and the main branch is now up to date.

**Comment by 1chooo** [comment]
> Got it. I have deleted that line and the main branch is now up to date. 

Awesome!!!
